# permissions for end users to edit certmanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator-k8s-home
    app.kubernetes.io/managed-by: kustomize
  name: core-certmanager-editor-role
rules:
- apiGroups:
  - core.scriptonbasestar.com
  resources:
  - certmanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.scriptonbasestar.com
  resources:
  - certmanagers/status
  verbs:
  - get
