# permissions for end users to view coredns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator-k8s-home
    app.kubernetes.io/managed-by: kustomize
  name: core-coredns-viewer-role
rules:
- apiGroups:
  - core.scriptonbasestar.com
  resources:
  - coredns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.scriptonbasestar.com
  resources:
  - coredns/status
  verbs:
  - get
