# permissions for end users to edit vaults.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sb-home-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: devsec-vault-editor-role
rules:
- apiGroups:
  - devsec.scriptonbasestar.com
  resources:
  - vaults
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devsec.scriptonbasestar.com
  resources:
  - vaults/status
  verbs:
  - get
