apiVersion: cache.scriptonbasestar.com/v1alpha1
kind: Memcached
metadata:
  labels:
    app.kubernetes.io/name: operator-k8s-home
    app.kubernetes.io/managed-by: kustomize
  name: memcached-sample
spec:
  # TODO(user): Add fields here
